# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [13]:
np.version.version

'1.19.5'

In [14]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [33]:
vn= np.zeros(10)
print(vn)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [40]:
vn[4]=1
print(vn)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [31]:
z = np.linspace(10,50,40)
print(z)

[10.         11.02564103 12.05128205 13.07692308 14.1025641  15.12820513
 16.15384615 17.17948718 18.20512821 19.23076923 20.25641026 21.28205128
 22.30769231 23.33333333 24.35897436 25.38461538 26.41025641 27.43589744
 28.46153846 29.48717949 30.51282051 31.53846154 32.56410256 33.58974359
 34.61538462 35.64102564 36.66666667 37.69230769 38.71794872 39.74358974
 40.76923077 41.79487179 42.82051282 43.84615385 44.87179487 45.8974359
 46.92307692 47.94871795 48.97435897 50.        ]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [39]:
z_reverse = z[::-1]
print(z_reverse)

[50.         48.97435897 47.94871795 46.92307692 45.8974359  44.87179487
 43.84615385 42.82051282 41.79487179 40.76923077 39.74358974 38.71794872
 37.69230769 36.66666667 35.64102564 34.61538462 33.58974359 32.56410256
 31.53846154 30.51282051 29.48717949 28.46153846 27.43589744 26.41025641
 25.38461538 24.35897436 23.33333333 22.30769231 21.28205128 20.25641026
 19.23076923 18.20512821 17.17948718 16.15384615 15.12820513 14.1025641
 13.07692308 12.05128205 11.02564103 10.        ]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [54]:
m = np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [55]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [61]:
nr= np.random
nr.rand(27).reshape(3,3,3)
print(n)

[[[0.5190406  0.84923071 0.74079599]
  [0.02190672 0.46846969 0.40007769]
  [0.18579405 0.30849201 0.45214232]]

 [[0.90937056 0.80729445 0.1296197 ]
  [0.36062405 0.59757158 0.98850301]
  [0.59017544 0.07957521 0.14127611]]

 [[0.62706322 0.13271001 0.20011736]
  [0.38855933 0.03513569 0.29566284]
  [0.46785997 0.25672857 0.49985209]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [111]:
n = nr.randn(10,10)
n_max = n.max()
n_min = n.min()
print(n)
print("Max:{}".format(n_max))
print("Min:{}".format(n_min))

[[ 1.29562323 -3.0757008   1.08594025  0.61967657 -0.43635401  0.75295001
  -0.22898626  1.04459934 -0.09550802 -0.42549883]
 [ 1.17789399  0.13062452  0.74564817 -2.01986117  1.58933988 -2.6120914
   0.72376838 -0.79829558 -0.37608997 -0.80159131]
 [-1.02486369  0.2932188  -1.46694438  0.32319636 -1.65876919 -0.65749372
  -0.63266365  0.72873553 -0.86563298  0.19394647]
 [-0.74887805 -1.781476   -0.67192465 -0.78499317 -0.39337665 -1.8171191
  -0.28268983 -1.52157178 -0.65754201 -0.1830735 ]
 [-0.18857847  0.30708132 -0.06403928  1.83751895  1.63986558 -2.13104348
  -0.56193897  1.02231899  0.29404582 -1.54971048]
 [ 1.99951086 -0.30706094 -0.44045677  1.01102368  0.79065298  1.37825909
   1.56824514  1.35991125 -0.64342418 -0.21486215]
 [-0.16629906  0.79329008  0.51224213  0.03029423 -1.01391535  0.22310413
  -0.41393401  1.19291387  0.31392207 -0.75076027]
 [-0.34338965 -0.01544292  0.68438723 -0.212639   -0.60864504  1.17715718
  -1.71755715 -1.13011456 -0.13373395  0.07473992]
 [

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [129]:
d = np.array([1,2,3,4])
e = np.diag(d,-1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [85]:
l = nr.rand(5)
s= np.sum(l)
print(l)
print(s)

[0.26992474 0.93878793 0.44607689 0.59146903 0.50796105]
2.754219629172173


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [76]:
m = np.mean(l)
print(l)
print(m)

[0.2860681  0.45021443 0.47898447 0.68627929 0.82453968]
0.5452171935478096


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [96]:
l = [x for x in range(11)]
np.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [103]:
print(np.linspace(0,1,10, False))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [110]:
A= np.linspace(0,5,5)
B= np.linspace(1,6,5)
print(A == B)

[False False False False False]


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [133]:
a=np.arange(10, dtype='float32')
print(a.dtype)
a=a.astype('int32')
print(a.dtype)

float32
int32


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [ ]:
(x - mean(x))/ecart_type(x)

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)