In [1]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [2]:
rdm_mat = np.random.rand(2,2)
print(rdm_mat)

[[0.26749811 0.02563888]
 [0.84102628 0.94129872]]


Donner le type de la variable rdm_mat

In [4]:
print(rdm_mat.dtype)

float64


Donner la somme des éléments de ce tableau 2D

In [5]:
print(rdm_mat.sum())

2.0754619823092773


Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [6]:
np.max(rdm_mat, axis= 1)

array([0.26749811, 0.94129872])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [ ]:
np.max(rdm_mat, axis=0)

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [14]:
print(rdm_mat)
max_rdm = np.array([])

for cell in rdm_mat:
    max_rdm = np.append(max_rdm, np.max(cell))
    
print(max_rdm)
    

[[0.26749811 0.02563888]
 [0.84102628 0.94129872]]
[0.26749811 0.94129872]


On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [15]:
rdm_vect = np.random.randn(100)
rdm_vect.shape
print(rdm_vect)

[-3.94887753e-01  7.70805957e-01 -1.65215550e+00  1.81398917e+00
 -3.48033361e-01  3.00224009e-01  2.21677961e-01  1.08377499e+00
  4.14979845e-02  7.90781524e-01 -3.53416800e-01  1.16570481e+00
 -1.07221401e+00  4.74634569e-01 -2.30698058e-01  1.45491919e+00
  9.24655361e-01  7.08294579e-02  4.67481232e-01 -1.11913557e+00
 -5.69946797e-01  1.55167664e+00 -3.35063183e-01 -1.24276634e+00
 -1.48804087e-01 -2.40590825e-01 -2.26043830e-01 -1.02778780e+00
 -2.26728831e+00 -1.31864368e+00  6.31477368e-01 -2.39463043e+00
 -2.19678019e-01  1.94193299e-01  4.29900583e-01 -1.41663383e+00
  8.13079367e-02  2.83340475e-01  3.45190395e-01  1.35973964e+00
 -3.72559334e-01  5.20009950e-01  6.94640171e-02  1.49245461e+00
  1.12821794e-01 -4.85884788e-01  1.54180582e+00  4.50080471e-01
  1.89498394e-01  1.26055734e+00  6.58280000e-01  1.99907732e+00
  1.02010440e+00 -5.55423057e-01  1.56662729e+00  1.77704945e-01
 -6.31313748e-01  8.81826622e-01  4.74623159e-01 -2.31402800e+00
 -6.74007082e-01  9.17367

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [25]:
np.argmax(rdm_vect)

89

Afficher cette valeur 

In [33]:
"1er"
print(np.max(rdm_vect))
"2ème"
print(rdm_vect[np.argmax(rdm_vect)])

2.2424107960017583
2.2424107960017583


Convertir le vecteur en un tableau 10, 10

In [35]:
m = rdm_vect.reshape(10,10)
print(m)

[[-3.94887753e-01  7.70805957e-01 -1.65215550e+00  1.81398917e+00
  -3.48033361e-01  3.00224009e-01  2.21677961e-01  1.08377499e+00
   4.14979845e-02  7.90781524e-01]
 [-3.53416800e-01  1.16570481e+00 -1.07221401e+00  4.74634569e-01
  -2.30698058e-01  1.45491919e+00  9.24655361e-01  7.08294579e-02
   4.67481232e-01 -1.11913557e+00]
 [-5.69946797e-01  1.55167664e+00 -3.35063183e-01 -1.24276634e+00
  -1.48804087e-01 -2.40590825e-01 -2.26043830e-01 -1.02778780e+00
  -2.26728831e+00 -1.31864368e+00]
 [ 6.31477368e-01 -2.39463043e+00 -2.19678019e-01  1.94193299e-01
   4.29900583e-01 -1.41663383e+00  8.13079367e-02  2.83340475e-01
   3.45190395e-01  1.35973964e+00]
 [-3.72559334e-01  5.20009950e-01  6.94640171e-02  1.49245461e+00
   1.12821794e-01 -4.85884788e-01  1.54180582e+00  4.50080471e-01
   1.89498394e-01  1.26055734e+00]
 [ 6.58280000e-01  1.99907732e+00  1.02010440e+00 -5.55423057e-01
   1.56662729e+00  1.77704945e-01 -6.31313748e-01  8.81826622e-01
   4.74623159e-01 -2.31402800e+00

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [41]:
print(np.mean(m, axis=1))

[ 0.2627675   0.17827602 -0.58252582 -0.07057926  0.47782483  0.32774789
  0.56272953 -0.0221251   0.5952628   0.0817501 ]


Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [42]:
print(np.mean(m, axis=0))

[-0.07138302  0.23858479  0.07491946  0.43083751  0.47176954  0.23887412
  0.16025638  0.14174295 -0.11205118  0.23757795]


Calculer la somme pour chaque ligne (sans boucles)

In [43]:
print(np.sum(m, axis=1))

[ 2.62767499  1.78276019 -5.82525821 -0.70579258  4.77824828  3.27747893
  5.62729526 -0.22125102  5.95262799  0.81750104]


Calculer la somme pour chaque colonne (sans boucles)

In [40]:
print(np.sum(m, axis=0))

[-0.71383022  2.38584787  0.74919463  4.30837508  4.71769537  2.38874124
  1.60256377  1.41742946 -1.12051182  2.37577947]
